"""Initial Migration

Revision ID: b302225c90a1
Revises: 
Create Date: 2020-08-24 23:05:30.170570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b302225c90a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('election')
    op.drop_table('user')
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('votes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='question_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canVote', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('boardMember', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_table('election',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('questions', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('hasVoted', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='election_pkey')
    )
    # ### end Alembic commands ###
